repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.941'  # Use the sha / tag to point at specific version
    hooks:
    -   id: mypy
        additional_dependencies: ['types-requests', 'types-urllib3']
-   repo: https://github.com/psf/black
    rev: '22.1.0'
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: '4.0.1'
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.1.0'
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
